from enum import Enum


class ExportProspectsBodyFormat(str, Enum):
    COMPANY_GENERIC_CSV = "COMPANY_GENERIC_CSV"
    COMPANY_LI_ADS_CSV = "COMPANY_LI_ADS_CSV"
    DOMAIN_AGENT_CSV = "DOMAIN_AGENT_CSV"
    GOOGLE_MAPS_CSV = "GOOGLE_MAPS_CSV"
    LI_COMPANY_URL_FIXUP = "LI_COMPANY_URL_FIXUP"
    LI_PROFILE_URL_FIXUP = "LI_PROFILE_URL_FIXUP"
    PROSPECT_GENERIC_CSV = "PROSPECT_GENERIC_CSV"
    PROSPECT_GOOGLE_ADS_CSV = "PROSPECT_GOOGLE_ADS_CSV"
    PROSPECT_LI_ADS_CSV = "PROSPECT_LI_ADS_CSV"
    PROSPECT_META_ADS_CSV = "PROSPECT_META_ADS_CSV"

    def __str__(self) -> str:
        return str(self.value)
