from enum import Enum


class GetAudienceStatusResponse200OutputCreationMethod(str, Enum):
    BATCH_ENRICHMENT = "BATCH_ENRICHMENT"
    CLONED = "CLONED"
    COMPANY_UPLOAD = "COMPANY_UPLOAD"
    FOLLOW_ME = "FOLLOW_ME"
    INDIVIDUAL_SALES_NAV_SCRAPE = "INDIVIDUAL_SALES_NAV_SCRAPE"
    MERGE_AUDIENCES = "MERGE_AUDIENCES"
    NORMAL = "NORMAL"
    PROSPECT_UPLOAD = "PROSPECT_UPLOAD"
    SALES_NAV_COMPANIES = "SALES_NAV_COMPANIES"
    SALES_NAV_PROFILES = "SALES_NAV_PROFILES"
    START_FROM_PROSPECTS = "START_FROM_PROSPECTS"

    def __str__(self) -> str:
        return str(self.value)
