from enum import Enum


class GetEnrichmentStatusResponse200OutputCurrentStage(str, Enum):
    CLEANING_NAMES = "CLEANING_NAMES"
    DONE = "DONE"
    EXPORTING_CSV = "EXPORTING_CSV"
    FAILED = "FAILED"
    FETCHING_CONTACT_DETAILS = "FETCHING_CONTACT_DETAILS"
    NOT_STARTED = "NOT_STARTED"
    RESUBMITTING_AUDIENCE = "RESUBMITTING_AUDIENCE"
    RUNNING_LIVE_ENRICH = "RUNNING_LIVE_ENRICH"
    RUNNING_SALES_NAV = "RUNNING_SALES_NAV"
    STARTED = "STARTED"
    VALIDATING_CONTACT_DETAILS = "VALIDATING_CONTACT_DETAILS"

    def __str__(self) -> str:
        return str(self.value)
