from enum import StrEnum


class LiteReverseEmailLookupResponse200OutputRejectionType0Reason(StrEnum):
    AUTOGENERATED_ICLOUD_EMAIL = "autogenerated_icloud_email"
    BOT_FARM_EMAIL = "bot_farm_email"
    DIGITS_ONLY_USERNAME = "digits_only_username"
    DISPOSABLE_OR_ANONYMOUS_EMAIL = "disposable_or_anonymous_email"
    INVALID_TLD = "invalid_tld"
    JUNK_USERNAME = "junk_username"
    MAILING_LIST = "mailing_list"
    ROLE_BASED_MAILBOX = "role_based_mailbox"
    SPAM_DOMAIN = "spam_domain"

    def __str__(self) -> str:
        return str(self.value)
