from enum import Enum


class ReverseEmailLookupResponse200OutputRejectionType0Reason(str, Enum):
    AUTOGENERATED_ICLOUD_EMAIL = "autogenerated_icloud_email"
    DIGITS_ONLY_USERNAME = "digits_only_username"
    DISPOSABLE_OR_ANONYMOUS_EMAIL = "disposable_or_anonymous_email"
    INVALID_TLD = "invalid_tld"
    JUNK_USERNAME = "junk_username"
    ROLE_BASED_MAILBOX = "role_based_mailbox"
    SPAM_DOMAIN = "spam_domain"

    def __str__(self) -> str:
        return str(self.value)
